### ISSUE TITLE
AnkiConnect request fails

### ISSUE THREAD

**Issue by andrewcurriebroughton** [Pedro-Bronsveld/anki-preview-reloader#1]
I keep getting the following error message when making changes from the VSCode extension:

Failed to save 'Front.template.anki': Unable to write file 'anki-editor:/Note Types/Vocabulary/Card 1/Front.template.anki' (Error: Anki-connect request failed: "on_model_updated() got multiple values for argument '_old'")

AnkiConnect 23.10.29.0
Anki 23.10

Possibly related to latest AnkiConnect release which includes this merged PR: https://github.com/FooSoft/anki-connect/pull/382.

**Comment by Pedro-Bronsveld** [comment]
Thanks for letting me know my add-on broke with the latest Anki update.

The new Anki version added an extra argument to one of the functions wrapped by the add-on, which caused the error.

The problem has been fixed in version 1.0.1 and published to AnkiWeb.
