### ISSUE TITLE
Anki preview Reloader does not appear

### ISSUE THREAD

**Issue by driesdep** [Pedro-Bronsveld/anki-preview-reloader#3]
![Schermafdruk 2024-03-01 01 16 31](https://github.com/Pedro-Bronsveld/anki-preview-reloader/assets/81444996/2ababeeb-6d73-4247-883f-76862cc089b3)
i have download the add-on in anki . (Anki preview reloader)
In visual studio code i have Anki Editor.
And anki connect is also in my list of add-ons of Anki.

The anki editor is working clearly, but i have no preview, nor template who is appearing.
I don't know what's the problem.

I work with the firefox browser. If you could let me know if you have an idea ?
Thanks

**Comment by Pedro-Bronsveld** [comment]
Hi,

The preview window is not part of these extensions. Anki's own template preview window can be opened from the menu bar in Anki by going to `Tools` > `Manage Note Types`, then select the note type you want to edit, and press the `Cards` button.

Alternatively, you can open the preview of a specific card by opening Anki's card browser, selecting a card/note, and clicking the `Preview` button.

The anki-preview-reloader add-on adds code to automatically reload these built-in preview windows when the card template is updated externally. So to get a preview of your card, you'll have to open VSCode and Anki's preview window side by side.

I hope this solves your issue.
